# Generated by Django 4.0.5 on 2022-07-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
