# Generated by Django 4.0.5 on 2022-07-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
